import { normalize } from 'polished';
import { createGlobalStyle } from 'styled-components';

export const GlobalStyle = createGlobalStyle`
  ${normalize()}

  * {
    margin: 0;
  }

  :root {
    /* Colors Generated by https://coolors.co/ff6b35-1a659e-ffae03-403f4c-d8d8d8 */
    --primary: rgba(26, 101, 158, 1);
    --secondary: rgba(255, 107, 53, 1);
    --tertiary: rgba(102, 119, 97, 1);
    --black: rgba(64, 63, 76, 1);
    --white: rgba(216, 216, 216, 1);
  }

  html {
    font-family: 'Roboto', sans-serif;
    font-size: 100%;
    color: var(--black);
  }

  body {
    background-color: var(--white);
  }

  #__next {
    height: 100vh;
    width: 100vw;
    display: flex;
    flex-direction: column;
  }

  h1, h2, h3, p, p.description {
    margin: .5em 0 .25em 0;
  }

  h1 {
    font-size: 4.236rem;
  }

  h2 {
    font-size: 2.618rem;
  }

  h3 {
    font-size: 1.618rem;
  }

  p {
    font-size: 1rem;
  }

  p.description {
    font-size: .618rem;
  }

  button {
    font-size: 1em;
    width: fit-content;
    padding: .75rem 1.25rem;
    border-radius: 5px;
  }

  h1.pulse {
    border: 0.25rem solid var(--black);
    animation: pulse 5s infinite;
  }

  @keyframes pulse {
    0%,
    100% {
      color: var(--white);
      border-color: var(--white);
    }
    25%,
    75% {
      color: var(--black);
      border-color: var(--black);
    }
  }

  a {
    color: var(--primary);
  }

  a:hover {
    opacity: 0.6;
  }
`;
